apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: k8sblockpodprivilegedcontainer
  labels:
    app.kubernetes.io/name: kubernetes-opa-library
    app.kubernetes.io/created-by: ssbostan
spec:
  crd:
    spec:
      names:
        kind: K8sBlockPodPrivilegedContainer
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8sblockpodprivilegedcontainer

        violation[{"msg": msg}] {
          check_pod_privileged_container == true
          msg := "Creating privileged containers is restricted on this namespace."
        }

        check_pod_privileged_container {
          input.review.object.spec.containers[_].securityContext.privileged == true
        }

        check_pod_privileged_container {
          input.review.object.spec.ephemeralContainers[_].securityContext.privileged == true
        }

        check_pod_privileged_container {
          input.review.object.spec.initContainers[_].securityContext.privileged == true
        }
