apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: k8sblockpodaddlinuxcapabilities
  labels:
    app.kubernetes.io/name: kubernetes-opa-library
    app.kubernetes.io/created-by: ssbostan
spec:
  crd:
    spec:
      names:
        kind: K8sBlockPodAddLinuxCapabilities
      validation:
        openAPIV3Schema:
          type: object
          properties:
            allowedLinuxCapabilities:
              type: array
              items:
                type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8sblockpodaddlinuxcapabilities

        import future.keywords.in

        violation[{"msg": msg}] {
          some container in containers
          check_container_capabilities(container.securityContext.capabilities.add)
          msg := "Adding new linux capabilities to containers is not allowed in this namespace."
        }

        check_container_capabilities(capabilities) {
          some capability in capabilities
          not check_container_allowed_capability(capability)
        }

        check_container_allowed_capability(capability) {
          some allowedCapability in input.parameters.allowedLinuxCapabilities
          capability == allowedCapability
        }

        containers[container] {
          container := input.review.object.spec.containers[_]
        }

        containers[container] {
          container := input.review.object.spec.ephemeralContainers[_]
        }

        containers[container] {
          container := input.review.object.spec.initContainers[_]
        }
