enableK8sBlockPodOSNameWindows: true
enableK8sBlockPodWindowsHostProcess: true

enableK8sBlockPodHostIPCNamespace: true
enableK8sBlockPodHostNetworkNamespace: true
enableK8sBlockPodHostPIDNamespace: true
enableK8sBlockPodHostIPHostPortContainer: true

enableK8sBlockPodProcMountContainer: true
enableK8sBlockPodPrivilegedContainer: true
enableK8sBlockPodContainerPrivilegeEscalation: true
enableK8sBlockPodUnconfinedSeccompProfileContainer: true
enableK8sBlockPodUnconfinedAppArmorProfileContainer: true
enableK8sBlockPodRunRootUserContainer: true
enableK8sBlockPodAddLinuxCapabilities: true
enableK8sBlockPodAddSysctlParameter: true

enableK8sBlockServiceLoadBalancer: true
enableK8sBlockServiceNodePort: true

enableK8sBlockPodUntrustedImageRegistries: true
trustedImageRegistries:
  - docker.io
  - gcr.io

enableK8sBlockNamespaceWithoutLabelPrefix: true
namespacePrefixLabelName: k8s.io/project

enableK8sBlockNamespaceWithoutRequiredLabels: true
namespaceRequiredLabels:
  - k8s.io/project

enableK8sBlockPodVolumeTypes: true
blockedPodVolumeTypes:
  - hostPath
  - emptyDir
  - ephemeral
  - flexVolume
  - flocker

excludedNamespaces:
  - gatekeeper-system
  - kube-system
  - kube-node-lease
  - kube-public
