{{ if .Values.enableK8sBlockServiceLoadBalancer }}
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sBlockServiceLoadBalancer
metadata:
  name: default
  labels:
    app.kubernetes.io/name: kubernetes-opa-library
    app.kubernetes.io/created-by: ssbostan
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Service"]
    excludedNamespaces:
{{ toYaml .Values.excludedNamespaces | indent 6 }}
{{ end }}
