{{ if .Values.enableK8sBlockPodUnconfinedSeccompProfileContainer }}
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sBlockPodUnconfinedSeccompProfileContainer
metadata:
  name: k8s-block-pod-unconfined-seccomp-profile-container
  labels:
    app.kubernetes.io/name: kubernetes-opa-library
    app.kubernetes.io/created-by: ssbostan
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    excludedNamespaces:
{{ toYaml .Values.excludedNamespaces | indent 6 }}
{{ end }}
