{{ if .Values.enableK8sBlockPodAddLinuxCapabilities }}
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sBlockPodAddLinuxCapabilities
metadata:
  name: default
  labels:
    app.kubernetes.io/name: kubernetes-opa-library
    app.kubernetes.io/created-by: ssbostan
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    excludedNamespaces:
{{ toYaml .Values.excludedNamespaces | indent 6 }}
  parameters:
    allowedCapabilities:
{{ toYaml .Values.allowedLinuxCapabilities | indent 6 }}
{{ end }}
