{{- if .Values.enableK8sBlockNamespaceWithoutRequiredLabels -}}
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sBlockResourceWithoutRequiredLabels
metadata:
  name: default
  labels:
    app.kubernetes.io/name: kubernetes-opa-library
    app.kubernetes.io/created-by: ssbostan
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Namespace"]
    excludedNamespaces:
      {{- toYaml .Values.excludedNamespaces | nindent 6 }}
  parameters:
    labels:
      {{- toYaml .Values.namespaceRequiredLabels | nindent 6 }}
{{- end -}}
