{{- if .Values.enableK8sBlockServiceNodePort -}}
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sBlockServiceNodePort
metadata:
  name: default
  labels:
    app.kubernetes.io/name: kubernetes-opa-library
    app.kubernetes.io/created-by: ssbostan
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Service"]
    excludedNamespaces:
      {{- toYaml .Values.excludedNamespaces | nindent 6 }}
{{- end -}}
